# Generated by Django 6.0 on 2026-01-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_shopuser_address_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
    ]
