# Generated by Django 6.0 on 2025-12-31 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_id_alter_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='futures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.productfuture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(default=0)),
        ),
    ]
