# Generated by Django 6.0 on 2025-12-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_futures_alter_product_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
