# Generated by Django 6.0 on 2025-12-31 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_new_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='futures',
        ),
        migrations.AddField(
            model_name='productfuture',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futures', to='shop.product'),
        ),
    ]
