# Generated by Django 6.0 on 2026-01-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
    ]
