# Generated by Django 6.0 on 2026-01-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
