# Generated by Django 6.0 on 2026-01-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
