# Generated by Django 6.0 on 2026-01-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_buyer_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('review', 'در صف بررسی'), ('confirm', 'تایید سفارش'), ('delivery', 'تحویل مرسوله'), ('preparation', 'اماده سازی سفارش'), ('post', 'تحویل به پست'), ('cancel', 'عدم تایید سفارش')], default='review', max_length=250),
        ),
    ]
