# Generated by Django 6.0 on 2026-01-29 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_address'),
        ('shop', '0016_alter_category_id_alter_image_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_prods', to='shop.product'),
        ),
    ]
